[package]
name = "kindlenotes2anki"
version = "0.17.2"
authors = ["jdambron"]
description = "A tool to import kindle clippings file to Anki"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
csv = "1"
serde = { version = "1", features = ["derive"] }
toml = "1"
ureq = { version = "3", default-features = false, features = ["json"] }

[dev-dependencies]
tempfile = "3"

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
